In [32]:
import pandas as pd
import numpy as np
import matplotlib as plt
from sklearn.model_selection import train_test_split
from scipy.stats import norm
import warnings
warnings.filterwarnings("ignore")
import random

In [33]:
Header = ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation', 'relationship', 'race', 'sexl', 'capital-gain', 'capital-loss', 'hours-per-week','native-country','income']
data = pd.read_csv("adult.data", names = Header)
data

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sexl,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [34]:
test = pd.read_csv("adult.test", names = Header)
test

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sexl,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K.
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K.
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K.
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K.
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16276,39,Private,215419,Bachelors,13,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,36,United-States,<=50K.
16277,64,?,321403,HS-grad,9,Widowed,?,Other-relative,Black,Male,0,0,40,United-States,<=50K.
16278,38,Private,374983,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States,<=50K.
16279,44,Private,83891,Bachelors,13,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,Male,5455,0,40,United-States,<=50K.
16280,35,Self-emp-inc,182148,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,60,United-States,>50K.

In [35]:
#Replace missing values with mode
def preprocess(data):
    print("Count of missing values before Preprocessing: " + str(data[data==' ?'].count().sum()))
    print("Columns containing missing values: " + str(data.columns[data.isin([' ?']).any()]))
    data['workclass'].replace(' ?', data['workclass'].mode()[0], inplace=True)
    data['occupation'].replace(' ?', data['occupation'].mode()[0], inplace=True)
    data['native-country'].replace(' ?', data['native-country'].mode()[0], inplace=True)
    print("Count of missing values after Preprocessing: "+str(data[data==' ?'].count().sum()))
    return data

In [36]:
#Remove rows with missing values
def preprocess2(data):
    data = data[data.workclass != ' ?']
    data = data[data.occupation != ' ?']
    data = data[data['native-country'] != ' ?']
    return data

In [37]:
data = preprocess(data)
test = preprocess(test)
print(data.shape)
print(test.shape)

Count of missing values before Preprocessing: 4262
Columns containing missing values: Index(['workclass', 'occupation', 'native-country'], dtype='object')
Count of missing values after Preprocessing: 0
Count of missing values before Preprocessing: 2203
Columns containing missing values: Index(['workclass', 'occupation', 'native-country'], dtype='object')
Count of missing values after Preprocessing: 0
(32561, 15)
(16281, 15)

In [38]:
def train_test(X, y, test_size=0.2, random_state=42):
    n_samples = X.shape[0]
    n_test = int(n_samples * test_size)
    if random_state is not None:
        random.seed(random_state)
    indices = list(range(n_samples))
    random.shuffle(indices)
    test_indices = indices[:n_test]
    train_indices = indices[n_test:]
    X_train = X[train_indices]
    X_test = X[test_indices]
    y_train = y[train_indices]
    y_test = y[test_indices]
    return X_train, X_test, y_train, y_test

In [39]:
X_train = data.drop('income', axis=1)
y_train = data['income']
X_test = test.drop('income', axis=1)
y_test = test['income']
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(32561, 14)
(16281, 14)
(32561,)
(16281,)

In [40]:
for i in range(y_test.shape[0]):
    y_test.iloc[i] = y_test.iloc[i].replace('.', '')

# Naive Bayes Classifier

In [41]:
def prior_prob(y_train):
    n_samples = len(y_train)
    print("Number of samples: " + str(n_samples))
    prior = {}
    for c in np.unique(y_train):
        prior[c] = y_train[y_train == c].shape[0] / n_samples
    return prior

def conditional_prob(X_train, y_train, smoothing = False):
    n_samples, n_features = X_train.shape
    unique_classes = np.unique(y_train)
    conditional_probabilities = {}
    
    for col in X_train.columns:
        probabilities_c = {}
        for c in unique_classes:
            X_c = X_train[y_train == c]
            n_c = X_c.shape[0]
            if X_c[col].dtype == np.object:
                value_counts = X_c[col].value_counts()
                if smoothing:
                    probs = (value_counts + 1) / (n_c + len(value_counts))
                else:
                    probs = value_counts / n_c
                probabilities_c[c] = probs.to_dict()
            else:
                mean = X_c[col].mean()
                std = X_c[col].std()
                probabilities_c[c] = (mean, std)
        
        conditional_probabilities[col] = probabilities_c
    
    return conditional_probabilities

def predict(instance, conditional, y_train, prior):
    unique_classes = np.unique(y_train)
    prediction = ' '
    best_prob = -np.inf
    for c in unique_classes:
        prob = 0
        for col in instance.index:
            if type(instance[col]) == str:
                if(instance[col] in conditional[col][c]):
                    prob += np.log(conditional[col][c][instance[col]])
            else:
                mean, std = conditional[col][c]
                prob += np.log(norm.pdf(instance[col], mean, std))
        if prob + np.log(prior[c]) > best_prob:
            best_prob = prob + np.log(prior[c])
            prediction = c
    return prediction

def evaluate(X_test, conditional, prior):
    predictions = []
    for i in range(len(X_test)):
        pred = predict(X_test.iloc[i], conditional, y_train, prior)
        predictions.append(pred)
    return predictions

def metrics(predictions, y_test):
    num_examples = len(predictions)
    true_positives = sum(p == ' <=50K' and t == ' <=50K' for p, t in zip(predictions, y_test))
    false_positives = sum(p == ' <=50K' and t == ' >50K' for p, t in zip(predictions, y_test))
    true_negatives = sum(p == ' >50K' and t == ' >50K' for p, t in zip(predictions, y_test))
    false_negatives = sum(p == ' >50K' and t == ' <=50K' for p, t in zip(predictions, y_test))
    
    accuracy = (true_positives + true_negatives) / num_examples
    precision = true_positives / (true_positives + false_positives) if (true_positives + false_positives) > 0 else 0
    recall = true_positives / (true_positives + false_negatives) if (true_positives + false_negatives) > 0 else 0
    f1_score = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0
    print("Accuracy: " + str(100 * accuracy))
    print("Precision: " + str(precision))
    print("Recall: " + str(recall))
    print("F1 Score: " + str(f1_score))

In [42]:
prior = prior_prob(y_train)
print(prior)
conditional = conditional_prob(X_train, y_train, True)
print(conditional)

Number of samples: 32561
{' <=50K': 0.7591904425539756, ' >50K': 0.2408095574460244}
{'age': {' <=50K': (36.78373786407767, 14.02008849082488), ' >50K': (44.24984058155847, 10.519027719851826)}, 'workclass': {' <=50K': {' Private': 0.783686509220317, ' Self-emp-not-inc': 0.07351989647363313, ' Local-gov': 0.05972986088644452, ' State-gov': 0.03825622775800712, ' Federal-gov': 0.023859592364930442, ' Self-emp-inc': 0.02001779359430605, ' Without-pay': 0.0006065998058880621, ' Never-worked': 0.00032351989647363315}, ' >50K': {' Private': 0.6569389575634, ' Self-emp-not-inc': 0.09239199694150631, ' Self-emp-inc': 0.07939339875111508, ' Local-gov': 0.07875621256531158, ' Federal-gov': 0.04740665222377979, ' State-gov': 0.045112781954887216}}, 'fnlwgt': {' <=50K': (190340.8651699029, 106482.27119468106), ' >50K': (188005.0, 102541.77547230694)}, 'education': {' <=50K': {' HS-grad': 0.35684831824062097, ' Some-college': 0.23872089262613194, ' Bachelors': 0.12673835705045278, ' 11th': 0.045116429495472184, ' Assoc-voc': 0.04131630012936611, ' 10th': 0.0352522639068564, ' Assoc-acdm': 0.03246280724450194, ' Masters': 0.03092658473479948, ' 7th-8th': 0.024539133247089263, ' 9th': 0.019728331177231564, ' 12th': 0.01621119016817594, ' 5th-6th': 0.012855756791720569, ' 1st-4th': 0.0065895860284605435, ' Prof-school': 0.006225743855109961, ' Doctorate': 0.004366106080206986, ' Preschool': 0.0021021992238033633}, ' >50K': {' Bachelors': 0.2828411405295316, ' HS-grad': 0.21334012219959267, ' Some-college': 0.17668024439918534, ' Masters': 0.12219959266802444, ' Prof-school': 0.0539714867617108, ' Assoc-voc': 0.04607942973523422, ' Doctorate': 0.03907841140529532, ' Assoc-acdm': 0.033859470468431775, ' 10th': 0.008019348268839105, ' 11th': 0.007764765784114053, ' 7th-8th': 0.005218940936863543, ' 12th': 0.004327902240325866, ' 9th': 0.003564154786150713, ' 5th-6th': 0.002163951120162933, ' 1st-4th': 0.0008910386965376783}}, 'education-num': {' <=50K': (9.595064724919094, 2.4361467923084), ' >50K': (11.611656676444332, 2.385128632665081)}, 'marital-status': {' <=50K': {' Never-married': 0.412221458324908, ' Married-civ-spouse': 0.3350588425607635, ' Divorced': 0.16099809924374167, ' Separated': 0.0388239576171796, ' Widowed': 0.036761434868766936, ' Married-spouse-absent': 0.015570024669389736, ' Married-AF-spouse': 0.0005661827152505358}, ' >50K': {' Married-civ-spouse': 0.85282874617737, ' Never-married': 0.06269113149847094, ' Divorced': 0.059123343527013254, ' Widowed': 0.010958205912334353, ' Separated': 0.008537206931702344, ' Married-spouse-absent': 0.00445973496432212, ' Married-AF-spouse': 0.0014016309887869521}}, 'occupation': {' <=50K': {' Prof-specialty': 0.15905231664914693, ' Adm-clerical': 0.13196409800274925, ' Craft-repair': 0.12820409153392093, ' Other-service': 0.1277189294089108, ' Sales': 0.10786771246058058, ' Exec-managerial': 0.08486294169968464, ' Machine-op-inspct': 0.07087410042855988, ' Handlers-cleaners': 0.051952777553165685, ' Transport-moving': 0.051669766313576455, ' Farming-fishing': 0.03557855583407455, ' Tech-support': 0.026117894396377458, ' Protective-serv': 0.0177488477399531, ' Priv-house-serv': 0.006024096385542169, ' Armed-Forces': 0.00036387159375758063}, ' >50K': {' Prof-specialty': 0.2611075747931254, ' Exec-managerial': 0.2506683640992998, ' Sales': 0.12527052832590707, ' Craft-repair': 0.11839592616168046, ' Adm-clerical': 0.06467218332272438, ' Transport-moving': 0.04086569064290261, ' Tech-support': 0.036155315085932525, ' Machine-op-inspct': 0.03195416931890516, ' Protective-serv': 0.02698917886696372, ' Other-service': 0.01756842775302355, ' Farming-fishing': 0.014767663908338637, ' Handlers-cleaners': 0.011075747931253979, ' Armed-Forces': 0.0002546148949713558, ' Priv-house-serv': 0.0002546148949713558}}, 'relationship': {' <=50K': {' Not-in-family': 0.30130227291110573, ' Husband': 0.2942651460001618, ' Own-child': 0.202297177060584, ' Unmarried': 0.13059128043355173, ' Other-relative': 0.038218878912885224, ' Wife': 0.03332524468171156}, ' >50K': {' Husband': 0.7543010067541736, ' Not-in-family': 0.1092137122467185, ' Wife': 0.09506817892188098, ' Unmarried': 0.02790875493819294, ' Own-child': 0.008665732126927488, ' Other-relative': 0.004842615012106538}}, 'race': {' <=50K': {' White': 0.8372093023255814, ' Black': 0.11073811931243681, ' Asian-Pac-Islander': 0.03089989888776542, ' Amer-Indian-Eskimo': 0.011162790697674419, ' Other': 0.009989888776541962}, ' >50K': {' White': 0.9072138669385674, ' Black': 0.04945195003823604, ' Asian-Pac-Islander': 0.035304613815957175, ' Amer-Indian-Eskimo': 0.004715778740759622, ' Other': 0.003313790466479735}}, 'sexl': {' <=50K': {' Male': 0.6119650513712482, ' Female': 0.3880349486287517}, ' >50K': {' Male': 0.8495473670789239, ' Female': 0.1504526329210761}}, 'capital-gain': {' <=50K': (148.75246763754046, 963.1393073649201), ' >50K': (4006.142456319347, 14570.37895128033)}, 'capital-loss': {' <=50K': (53.14292071197411, 310.75576909570026), ' >50K': (195.00153041703865, 595.4875739786379)}, 'hours-per-week': {' <=50K': (38.840210355987054, 12.318994641854877), ' >50K': (45.473026399693914, 11.012970930209278)}, 'native-country': {' <=50K': {' United-States': 0.9061427244457009, ' Mexico': 0.02467590161948225, ' Philippines': 0.005573280562174387, ' Puerto-Rico': 0.0041597673761156655, ' El-Salvador': 0.0039578369209644195, ' Germany': 0.003796292556843423, ' Canada': 0.0033520455555106823, ' Jamaica': 0.002907798554177941, ' Cuba': 0.002867412463147692, ' Dominican-Republic': 0.0027866402810871934, ' South': 0.002625095916966197, ' Vietnam': 0.0025443237349056986, ' Guatemala': 0.0025039376438754494, ' India': 0.0024635515528452, ' England': 0.0024635515528452, ' Columbia': 0.0023423932797544526, ' China': 0.002261621097693954, ' Poland': 0.0019789184604822097, ' Italy': 0.0019789184604822097, ' Haiti': 0.0016558297322402165, ' Japan': 0.0015750575501797181, ' Portugal': 0.001373127095028472, ' Nicaragua': 0.0013327410039982231, ' Taiwan': 0.001292354912967974, ' Peru': 0.0012115827309074755, ' Iran': 0.0010500383667864787, ' Ecuador': 0.0010096522757562295, ' Greece': 0.000888494002665482, ' Ireland': 0.0008077218206049837, ' Trinadad&Tobago': 0.0007269496385444853, ' France': 0.0007269496385444853, ' Laos': 0.000686563547514236, ' Thailand': 0.000646177456483987, ' Hong': 0.0006057913654537377, ' Outlying-US(Guam-USVI-etc)': 0.0006057913654537377, ' Cambodia': 0.0005250191833932393, ' Honduras': 0.0005250191833932393, ' Yugoslavia': 0.000444247001332741, ' Hungary': 0.000444247001332741, ' Scotland': 0.00040386091030249183, ' Holand-Netherlands': 8.077218206049837e-05}, ' >50K': {' United-States': 0.9286802030456853, ' Philippines': 0.007868020304568528, ' Germany': 0.005710659898477157, ' India': 0.0052030456852791875, ' Canada': 0.005076142131979695, ' Mexico': 0.004314720812182741, ' England': 0.003934010152284264, ' Italy': 0.003299492385786802, ' Cuba': 0.003299492385786802, ' Japan': 0.0031725888324873096, ' Taiwan': 0.00266497461928934, ' China': 0.00266497461928934, ' Iran': 0.0024111675126903555, ' South': 0.0021573604060913707, ' Puerto-Rico': 0.001649746192893401, ' Poland': 0.001649746192893401, ' France': 0.001649746192893401, ' Jamaica': 0.0013959390862944162, ' El-Salvador': 0.0012690355329949238, ' Greece': 0.0011421319796954316, ' Cambodia': 0.0010152284263959391, ' Hong': 0.0008883248730964467, ' Yugoslavia': 0.0008883248730964467, ' Ireland': 0.0007614213197969543, ' Vietnam': 0.0007614213197969543, ' Portugal': 0.0006345177664974619, ' Haiti': 0.0006345177664974619, ' Ecuador': 0.0006345177664974619, ' Thailand': 0.0005076142131979696, ' Hungary': 0.0005076142131979696, ' Guatemala': 0.0005076142131979696, ' Scotland': 0.0005076142131979696, ' Nicaragua': 0.00038071065989847715, ' Trinadad&Tobago': 0.00038071065989847715, ' Laos': 0.00038071065989847715, ' Columbia': 0.00038071065989847715, ' Dominican-Republic': 0.00038071065989847715, ' Peru': 0.00038071065989847715, ' Honduras': 0.0002538071065989848}}}

In [43]:
instance = X_test.iloc[1234, :]
print(predict(instance, conditional, y_train, prior))
print(y_test.iloc[1234])
print(predict(instance, conditional, y_train, prior) == y_test.iloc[1234])

 <=50K
 <=50K
True

In [45]:
print("Without smoothing")
prior = prior_prob(y_train)
conditional = conditional_prob(X_train, y_train, False)
predictions = evaluate(X_test, conditional, prior)
metrics(predictions, y_test)

Without smoothing
Number of samples: 32561
Accuracy: 82.93716602174314
Precision: 0.858170758845783
Recall: 0.9303578608765581
F1 Score: 0.8928075320265473

In [46]:
print("With smoothing")
prior = prior_prob(y_train)
conditional = conditional_prob(X_train, y_train, True)
predictions = evaluate(X_test, conditional, prior)
metrics(predictions, y_test)

With smoothing
Number of samples: 32561
Accuracy: 82.90031324857196
Precision: 0.8578951271972113
Recall: 0.9301970245275433
F1 Score: 0.8925843043444711

In [47]:
#implement label encoding for the categorical features
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for col in data.columns:
    if data[col].dtype == np.object:
        data[col] = le.fit_transform(data[col])

X_train, X_test, y_train, y_test = train_test_split(data.drop(['income'], axis=1), data['income'], test_size=0.33, random_state=42)

In [48]:
def metrics_lr_knn(predictions, y_test):
    num_examples = len(predictions)
    true_positives = sum(p == 1 and t == 1 for p, t in zip(predictions, y_test))
    false_positives = sum(p == 1 and t == 0 for p, t in zip(predictions, y_test))
    true_negatives = sum(p == 0 and t == 0 for p, t in zip(predictions, y_test))
    false_negatives = sum(p == 0 and t == 1 for p, t in zip(predictions, y_test))
    
    accuracy = (true_positives + true_negatives) / num_examples
    precision = true_positives / (true_positives + false_positives) if (true_positives + false_positives) > 0 else 0
    recall = true_positives / (true_positives + false_negatives) if (true_positives + false_negatives) > 0 else 0
    f1_score = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0
    print("Accuracy: " + str(100 * accuracy))
    print("Precision: " + str(precision))
    print("Recall: " + str(recall))
    print("F1 Score: " + str(f1_score))

# Logistic Regression

In [49]:
from sklearn.linear_model import LogisticRegression
logisticRegr = LogisticRegression()
logisticRegr.fit(X_train, y_train)
predictions = logisticRegr.predict(X_test)
metrics_lr_knn(predictions, y_test)

Accuracy: 80.37409268565048
Precision: 0.743109151047409
Recall: 0.2643137254901961
F1 Score: 0.3899334683251374

# K Nearest Neighbors

In [52]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(X_train_scaled, y_train)
predictions = knn.predict(X_test_scaled)
metrics_lr_knn(predictions, y_test)
# print('Accuracy of K-NN classifier on training set: {:.2f}'.format(knn.score(X_train_scaled, y_train)))
# print('Accuracy of K-NN classifier on test set: {:.2f}'.format(knn.score(X_test_scaled, y_test)))

Accuracy: 81.48148148148148
Precision: 0.6208981001727115
Recall: 0.563921568627451
F1 Score: 0.5910398684751337